server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d6rb0ch4tr6s7386h1u0-a.singapore-postgres.render.com/life4changedb
spring.datasource.username=root
spring.datasource.password=0qOinkHorDgGX40yEmd2oxa5THTmWUtJ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect